
version: '3.3'

services:
  database:
    container_name: database-dankycars
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: dankycars
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php-dankycars
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/dankycars

    depends_on:
      - database

  nginx:
    container_name: nginx-dankycars
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/dankycars
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
